    Create project 18/06/2566
    Create by moremoo
    Project : Numpy_index_slice_array

In [1]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.19.2


# 1-dim array

In [2]:
a = np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
a[-1]

90

In [3]:
a[:3]

array([ 0, 10, 20])

In [5]:
a[3:]

array([30, 40, 50, 60, 70, 80, 90])

In [6]:
a[3:6]

array([30, 40, 50])

# array [start:stop:step]

In [7]:
a[::2]

array([ 0, 20, 40, 60, 80])

In [8]:
a[-4:-1]

array([60, 70, 80])

In [9]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
a[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [12]:
a[-3:]

array([70, 80, 90])

In [13]:
a[-3::-1]

array([70, 60, 50, 40, 30, 20, 10,  0])