    Create project 19/06/2566
    Create by moremoo
    Project : Numpy_boolean_array

In [1]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.19.2


In [2]:
a = np.random.randint(0, 100, 20)
a

array([ 7, 63, 60, 32, 70,  3, 63, 85, 64, 91, 96, 41, 40, 87,  4, 11, 29,
       95, 91, 84])

# Array หาร 2 ลงตัว

In [3]:
a % 2 == 0

array([False, False,  True,  True,  True, False, False, False,  True,
       False,  True, False,  True, False,  True, False, False, False,
       False,  True])

In [4]:
a[a % 2 == 0]

array([60, 32, 70, 64, 96, 40,  4, 84])

In [5]:
(a % 2 == 0) & (a > 50)

array([False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False,  True])

In [6]:
a[(a % 2 == 0) & (a > 50)]

array([60, 70, 64, 96, 84])

# Array ลงท้ายด้วย 9

In [7]:
p = np.random.randint(1, 9999, 100)
p

array([2161, 1080, 6457, 9543, 2783, 7498, 3521, 8860, 2314,  709,  779,
       6142, 3634, 3526, 7486, 5919, 7054, 2862, 2955, 9710, 3719, 6589,
       3425, 4784, 7548, 7635, 5631, 1324, 6257, 9237, 1300, 9303, 8758,
       8719, 9696, 7108, 3206,  189, 1378, 8287, 8167, 7543, 4481, 1438,
       5177, 5669, 3298, 4625, 4778,  314,  247, 8140, 5771, 2315, 1143,
       4252, 3924, 6752, 2086,  149,   13, 6483, 4338, 9306, 6883, 4676,
       1475,  752, 9015, 7953, 3995, 7982, 2738, 7636, 6482, 2683, 6081,
       6619, 2793, 9618,  452,  713, 7437,  828,  123, 2421, 3000, 8240,
       9931, 2863,  243, 2618, 8108, 2238, 6530, 4859, 5091, 6832,  472,
       7272])

In [8]:
p % 10 == 9

array([False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False])

In [9]:
p[p % 10 == 9]

array([ 709,  779, 5919, 3719, 6589, 8719,  189, 5669,  149, 6619, 4859])

# อยากรู้ว่าอยู่ตำแหน่งไหน .where

In [10]:
np.where(p % 10 == 9)

(array([ 9, 10, 15, 20, 21, 33, 37, 45, 59, 77, 95]),)

In [11]:
p[23]

4784

In [12]:
p[np.where(p % 10 == 9)]

array([ 709,  779, 5919, 3719, 6589, 8719,  189, 5669,  149, 6619, 4859])

In [13]:
p[p % 10 == 9]

array([ 709,  779, 5919, 3719, 6589, 8719,  189, 5669,  149, 6619, 4859])