    Create project 18/06/2566
    Create by moremoo
    Project : Numpy_broadcasting

In [2]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.19.2


In [4]:
np.random.seed(9)
x = np.random.randint(1, 11, 5)
x

array([6, 7, 9, 7, 2])

In [6]:
z = (x - np.mean(x)) / np.std(x)
z

array([-0.08638684,  0.34554737,  1.2094158 ,  0.34554737, -1.81412369])

In [7]:
mu = np.mean(x)
mu

6.2

In [13]:
np.repeat(mu, 5)

array([6.2, 6.2, 6.2, 6.2, 6.2])

In [8]:
std = np.std(x)
std

2.3151673805580453

In [11]:
z = (x - mu) / std
z

array([-0.08638684,  0.34554737,  1.2094158 ,  0.34554737, -1.81412369])

# 2 Dim

In [16]:
a = np.arange(1, 7).reshape(3, -1) * 10
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [17]:
a + 5

array([[15, 25],
       [35, 45],
       [55, 65]])

# row column ไม่เท่ากัน

In [21]:
c = np.array([2, 10])
c

array([ 2, 10])

In [24]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [36]:
print(a.shape)
print(c.shape)
print(a.ndim)
print(c.ndim)

(3, 2)
(2,)
2
1


In [23]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [34]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [32]:
d = np.array([[2], [3], [4]])
d

array([[2],
       [3],
       [4]])

In [33]:
a + d

array([[12, 22],
       [33, 43],
       [54, 64]])