    Create project 02/07/2566
    Create by moremoo
    Project : Numpy

# List vs Array(ndarray)

    Array : สมาชิกมีชนิดข้อมูลเหมือนกัน
    List   : สมาชิกมีชนิดข้อมูลต่างกันได้
    
    Array : ขนาดแน่นอน เปลี่ยนแปลงชนาดไม่ได้
    List   : ขนาดยืดหยุ่นได้

In [1]:
import numpy as np

arr 0 มิติ

In [2]:
arr0 = np.array(1)
arr0.ndim
print(arr0, arr0.ndim)

1 0


In [3]:
arr1 = np.array([1, 2, 3])
arr1.ndim
print(arr1, arr1.ndim)

[1 2 3] 1


# List to Array

In [4]:
_List = [1, 2, 3, 4]
List_to_Array = np.array(_List)
print(List_to_Array)

[1 2 3 4]


# Tuple to Array

In [5]:
_Tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
Tuple_to_Array = np.array(_Tuple)
print(Tuple_to_Array)

[ 1  2  3  4  5  6  7  8  9 10]


# Array 2 มิติ

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.ndim
print(arr2, arr2.ndim)

[[1 2 3]
 [4 5 6]] 2


In [7]:
_List2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
List_to_Array = np.array(_List2)
print(List_to_Array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
_Tuple2 = ((2, 4), (6, 8), (10, 12))
Tuple_to_Array = np.array(_Tuple2)
print(Tuple_to_Array)

[[ 2  4]
 [ 6  8]
 [10 12]]


# การเข้าถึง Array (Index)

In [9]:
a = np.array([1, 2, 3, 4, 5])
print('array :', a)
print('array[0] :', a[0])
print('array[1] :', a[1])
print('array[4] :', a[4])
print('array[-1] :', a[-1])
print('array[-1] :', a[-5])

array : [1 2 3 4 5]
array[0] : 1
array[1] : 2
array[4] : 5
array[-1] : 5
array[-1] : 1


# array[row][col]

In [10]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print('array :', b)
print('array[1][1] :', b[1][1])
print('array[2][0] :', b[2][0])
print('array[0][0] :', b[0][0])
print('array[0][1] :', b[0][1])

array : [[1 2]
 [3 4]
 [5 6]]
array[1][1] : 4
array[2][0] : 5
array[0][0] : 1
array[0][1] : 2


In [11]:
b[0][1] = 500
print('array[0][1] :', b[0][1])
print('array :', b)

array[0][1] : 500
array : [[  1 500]
 [  3   4]
 [  5   6]]


# Array 3 มิติ

In [12]:
a = np.array([[[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
a

3


array([[[1, 2, 3],
        [4, 5, 6]]])

# a[dept][row][column]

In [13]:
a[0][1][1]

5

In [14]:
a[0][0][2]

3

In [15]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
b[1][0][1]

8

# Data Type

    1 Integer
    2 Float
    3 String
    4 Boolean
    5 Complex

In [17]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype)

[1 2 3 4 5] int32


In [18]:
a = np.array([1, 2, 3, 4, 5], dtype='int')
print(a, a.dtype)

[1 2 3 4 5] int32


In [19]:
a = np.array([1, 2, 3, 4, 5], dtype='float')
print(a, a.dtype)

[1. 2. 3. 4. 5.] float64


In [20]:
a = np.array([1, 2, 3, 4, 5], dtype='complex')
print(a, a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j] complex128


# Array 2 มิติ = Matrix

    Square Matrix เมตริกซ์จัตุรัส จำนวณ row=column
    Zero Matrix เมตริกซ์ศูนย์ สมาชิกทุกตัวเป็น 0
    Identity Matrix เมตริกซ์เอกลักษณ์ สมาชิกเส้นทะแยงมุมมีค่าเป็น 1 ที่เหลือ 0

In [21]:
a = np.zeros((3, 3)) #เมตริกซ์จัตุรัส
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [23]:
a = np.zeros(5, dtype='int')
a

array([0, 0, 0, 0, 0])

In [24]:
a = np.zeros((3, 4), dtype='int')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones Matrix

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.ones([3, 3], dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
np.ones((3, 3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Matrix Full

np.full(จำนวณ, ค่าของจำนวณ)

In [29]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [30]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [31]:
np.full((3, 3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.full((4, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [33]:
np.full((4, 5), 3, dtype='float')

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [34]:
np.full((4, 5), 3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

# Empty สุ่มค่า

In [35]:
np.empty([3, 4])

array([[1.09070970e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.71568210e-062, 2.98663305e-032,
        4.31507737e-061],
       [6.58254857e-038, 4.19332580e+175, 5.22488803e-037,
        7.40562781e-038]])

In [36]:
np.empty((4, 4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34598246e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

# Identity Matrix

In [37]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.identity(6, dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [41]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.eye(5, k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [44]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [45]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Linspace

np.linspace(start, stop, number)

In [46]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
np.linspace(1, 5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [48]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [49]:
np.linspace(1, 5, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 5])

# Arange

arange(start, stop, step, dtype)

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [52]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [53]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [54]:
np.arange(1, 10, 2, dtype='float')

array([1., 3., 5., 7., 9.])

In [55]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [56]:
np.arange(5, -5)

array([], dtype=int32)

In [57]:
np.arange(5, -5, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4])

In [58]:
np.arange(-5)

array([], dtype=int32)

# Random

สุ่มค่า 0-ก่อน1

In [59]:
np.random.random((2, 2))

array([[0.84060107, 0.31196216],
       [0.82110636, 0.83011191]])

In [60]:
np.random.random((4, 2))

array([[0.01111994, 0.76798777],
       [0.54030829, 0.81981007],
       [0.88010903, 0.24689576],
       [0.34616487, 0.37442748]])

# NumPy Attribute

In [61]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [62]:
print(a.ndim)
print(b.ndim)

1
2


In [63]:
print(a.dtype)
print(b.dtype)

int32
int32


In [64]:
print(a.shape)
print(b.shape)

(5,)
(3, 3)


In [65]:
print(a.size)
print(b.size)

5
9


In [66]:
print(a.itemsize)
print(b.itemsize)

4
4


In [67]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='complex')
c.dtype

dtype('complex128')

In [68]:
print(c.itemsize)

16


# Slice Array 1

a[start : end-1 : step]

In [69]:
a =  np.arange(1, 11)
print(a)
print(a[2])
print(a[:])
print(a[2:])
print(a[:8])
print(a[:: 2])
print(a[1:9: 2])

[ 1  2  3  4  5  6  7  8  9 10]
3
[ 1  2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]
[2 4 6 8]


# Slice Array 2

a[row, col] = a[start : end-1 : step , start : end-1 : step]

In [70]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [73]:
x[:2,:2]

array([[1, 2],
       [4, 5]])

# Index Operator

In [74]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
index = np.array([1, 5, 7])
index

array([1, 5, 7])

In [76]:
x[index]

array([2, 6, 8])

In [77]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
y[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [79]:
y[[0,2],[2,0]]

array([3, 7])

In [80]:
y[[0,1,2],[1]]

array([2, 5, 8])

In [81]:
y[[0,1,2],[0,1,2]]

array([1, 5, 9])

In [82]:
z = np.array([[1,-2,3],[4,-5,-6],[-7,8,9]])
z

array([[ 1, -2,  3],
       [ 4, -5, -6],
       [-7,  8,  9]])

In [83]:
z[z<0]

array([-2, -5, -6, -7])

In [84]:
z[z<0] * -1

array([2, 5, 6, 7])

# Reshape & Resize

จัดเรียงข้อมูลเหมือนกัน reshape เปลี่ยนแปลงข้อมูลไม่ถาวร
resize เปลี่ยนแปลงข้อมูลถาวร

In [85]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a.resize((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Flatten && ravel

In [89]:
a = np.array([[1,-2,3],[4,-5,-6],[-7,8,9]])
a

array([[ 1, -2,  3],
       [ 4, -5, -6],
       [-7,  8,  9]])

In [90]:
a.flatten()

array([ 1, -2,  3,  4, -5, -6, -7,  8,  9])

In [91]:
b = a.ravel()
b

array([ 1, -2,  3,  4, -5, -6, -7,  8,  9])

In [92]:
b.ravel()
b

array([ 1, -2,  3,  4, -5, -6, -7,  8,  9])

In [93]:
b[0] = 5 # ravel จะทำให้ array a เปลี่ยนแปลงข้อมูลด้วย
b

array([ 5, -2,  3,  4, -5, -6, -7,  8,  9])

In [94]:
a

array([[ 5, -2,  3],
       [ 4, -5, -6],
       [-7,  8,  9]])

# Transpose

In [95]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# สถิติ

In [97]:
a = np.array([1, 2, 3, 4, 5, 1])
a

array([1, 2, 3, 4, 5, 1])

In [98]:
a.sum()

16

In [99]:
a.prod() # ผลคูณ

120

In [100]:
a.mean()

2.6666666666666665

In [101]:
a.max()

5

In [102]:
a.min()

1

In [103]:
a.argmax() #หาตำแหน่งมากสุด

4

In [104]:
a.argmin()

0

In [106]:
b = np.array([[10, 20, 30], [40, 50, 90], [80, 100, 5]])
b

array([[ 10,  20,  30],
       [ 40,  50,  90],
       [ 80, 100,   5]])

In [107]:
np.min(b)

5

In [108]:
np.min(b, axis = 1)

array([10, 40,  5])

In [109]:
np.min(b, axis = 0)

array([10, 20,  5])

# Dot product

In [110]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [111]:
b = np.array([[11, 12], [13, 14]])
b

array([[11, 12],
       [13, 14]])

In [113]:
c = a.dot(b)
c

array([[37, 40],
       [85, 92]])

# Concatenate

In [114]:
a = np.array([3, 4, 2, 6])
a

array([3, 4, 2, 6])

In [116]:
b = np.array([8, 6, 5, 10])
b

array([ 8,  6,  5, 10])

In [118]:
np.concatenate((a, b))

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [119]:
np.append(a, 100)

array([  3,   4,   2,   6, 100])

In [120]:
np.append(a, b)

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [124]:
c = np.array([[1, 2], [4, 8]])
c

array([[1, 2],
       [4, 8]])

In [125]:
np.append(c, [[10], [20]], axis=1)

array([[ 1,  2, 10],
       [ 4,  8, 20]])

In [127]:
np.append(c, [[10, 20]], axis=0)

array([[ 1,  2],
       [ 4,  8],
       [10, 20]])

# Append & Insert

In [129]:
a = np.array([1, 2, 4, 8])
a

array([1, 2, 4, 8])

In [130]:
np.append(a, 40)

array([ 1,  2,  4,  8, 40])

In [131]:
np.insert(a, 1, 100)

array([  1, 100,   2,   4,   8])

In [134]:
np.insert(a, (1, 3), 100)

array([  1, 100,   2,   4, 100,   8])

In [133]:
np.insert(a, (1, 3), (100, 20))

array([  1, 100,   2,   4,  20,   8])

# Insert Array 2 มิติ

In [136]:
a = np.array([[1, 2], [10, 20]])
a

array([[ 1,  2],
       [10, 20]])

In [137]:
np.insert(a, 1, 100, axis=0)

array([[  1,   2],
       [100, 100],
       [ 10,  20]])

In [138]:
np.insert(a, 1, 100, axis=1)

array([[  1, 100,   2],
       [ 10, 100,  20]])

In [141]:
np.insert(a, 1, [100, 200], axis=1)

array([[  1, 100,   2],
       [ 10, 200,  20]])

In [142]:
np.insert(a, 1, [100, 200], axis=0)

array([[  1,   2],
       [100, 200],
       [ 10,  20]])

In [144]:
np.insert(a, 1, [[100, 200]], axis=0)

array([[  1,   2],
       [100, 200],
       [ 10,  20]])

# Delete

In [148]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
np.delete(a, 2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [150]:
a = np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [151]:
np.delete(a, 2, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [152]:
np.delete(a, 2, axis=1)

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

# Split

แยกข้อมูลใน Array ให้เท่าๆกัน

In [153]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [154]:
np.split(a, 4)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [156]:
a = a.reshape(5, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [157]:
np.hsplit(a, 4)

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20]])]

In [161]:
np.vsplit(a, 5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]