    Create project 18/06/2566
    Create by moremoo
    Project : การสร้างndarray (Numpy array)

In [2]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.19.2


In [3]:
a = np.array([24, 35, 18, 40])
a

array([24, 35, 18, 40])

In [6]:
list_a = [24, 35, 18, 40]
list_a

[24, 35, 18, 40]

In [7]:
b = np.array(list_a)
b

array([24, 35, 18, 40])

In [9]:
b.ndim # `Array กี่มิติ?

1

In [10]:
b.shape # สมาชิกกี่ตัว

(4,)

In [11]:
drink = np.array(['ไก่','กา','อาลาเลย์'])
drink

array(['ไก่', 'กา', 'อาลาเลย์'], dtype='<U8')

In [12]:
m = ['water', 20, 'cof', 50]
m

['water', 20, 'cof', 50]

In [13]:
m2 = np.array(m)
m2

array(['water', '20', 'cof', '50'], dtype='<U5')

# Array 2 มิติ

In [16]:
hw = np.array([[1, 2, 3], [4, 5, 6]])
hw

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
hw.shape # (row, col)

(2, 3)

In [19]:
hw.ndim

2

In [20]:
hw.size

6

In [21]:
z = np.zeros((4, 2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
x = np.ones((5, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
k = np.zeros((4, 3))
k[:] = 9
k

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [25]:
e = np.identity(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
e2 = np.eye(4)
e2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
f = np.arange(1, 11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
f2 = np.arange(1, 51)
f2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
f3 = np.reshape(f2, (10, 5))
f3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [34]:
f4 = np.reshape(np.arange(1, 51), (10, 5))
f4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])