    Create project 01/07/2566
    Create by moremoo
    Project : แก้สมการเชิงเส้นด้วย Matrix

In [1]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.19.2


มีเหรียญบาทและเหรียญห้า อยู่ 90 เหรียญ
    x + y = 90
จำนวนเงินรวม 250 บาท
    x + 5y = 250
ถามว่ามีเหรียญบาทและเหรียญห้ากี่เหรียญ

In [2]:
a = np.array([[1, 1], [1, 5]])
a

array([[1, 1],
       [1, 5]])

In [3]:
b = np.array([[90], [250]])
b

array([[ 90],
       [250]])

In [4]:
aI = np.linalg.inv(a)
aI

array([[ 1.25, -0.25],
       [-0.25,  0.25]])

In [5]:
c = np.dot(aI, b) # a*b != b*a
c

array([[50.],
       [40.]])

In [6]:
np.dot(a, c)

array([[ 90.],
       [250.]])

In [7]:
c2 = aI @ b # python 3.5 up
c2

array([[50.],
       [40.]])

# Matrix

ใช้ได้สำหรับเมตริก 2 มิติ

In [8]:
A = np.matrix([[1, 1], [1, 5]])
A

matrix([[1, 1],
        [1, 5]])

In [9]:
B = np.matrix([[90], [250]])
B

matrix([[ 90],
        [250]])

In [10]:
AI = A.I
AI

matrix([[ 1.25, -0.25],
        [-0.25,  0.25]])

In [11]:
C = AI * B
C

matrix([[50.],
        [40.]])

In [12]:
A.I * B

matrix([[50.],
        [40.]])

In [13]:
A * C

matrix([[ 90.],
        [250.]])